# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gcp-gcr: carecloud/gcp-gcr@0.1.3
  gcp-cli: circleci/gcp-cli@3.0.1
  gcp-gke: circleci/gcp-gke@2.0.0

jobs:
  native:
    docker:
      - image: cimg/gcp:2023.03
    steps:
      - checkout
      - run: gcloud --version
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
    - checkout
    # start proprietary DB using private Docker image
    # with credentials stored in the UI
    - run: docker build -t   
  gke:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - gcp-cli/install:
          components: kubectl
      - gcp-gke/rollout-image:
          container: webapp 
          deployment: flaskapp 
          image: webapp1 

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    example-workflow:
      jobs:
      - gcp-gcr/build-and-push-image:
          image: us-east1-docker.pkg.dev/mdidedda/flask-app/flaskapp
          registry-url: us-east1-docker.pkg.dev  



